build:
    cargo build --release
    cargo objcopy --release -- -O binary target/output.bin

set_on_bp:
    just build
    dfu-util -a 0 -s 0x08000000:leave -D target/output.bin


setup_ip:
    sudo nmcli connection add type ethernet ifname enp45s0 con-name \
        output_W5500 ipv4.method manual ipv4.addresses 192.168.1.20/24 \
        ipv4.never-default yes
    sudo nmcli connection up output_W5500
